### ISSUE TITLE
please help bro..

### ISSUE THREAD

**Issue by berkay55** [NoNameoN-A/TikTok-Follow-Heart-Views-Bot#15] opened 2020-12-16 23:52 UTC
hi,

what is this problem bro ://
https://prnt.sc/w4bhw5

**Comment by NoNameoN-A** [comment] 2020-12-17 06:32
Do you have Google Chrome?

**Comment by berkay55** [comment] 2020-12-17 12:14
yes, of course

**Comment by NoNameoN-A** [comment] 2020-12-17 12:51
Your google chrome version is equal if chromedriver version?

**Comment by berkay55** [comment] 2020-12-17 13:03
yes
87.0.4280.88

**Comment by NoNameoN-A** [comment] 2020-12-17 13:11
But the error is `This version of ChromeDriver only supports Chrome version 85` so i think that you have 2 different version... if your Chrom version is 87.0.4280.88 you must use it -> [ChromeDriver 87.0.4280.88](https://chromedriver.storage.googleapis.com/index.html?path=87.0.4280.88/)

**Comment by berkay55** [comment] 2020-12-17 19:03
thanks bro, but i'm not worked
502 error: https://prnt.sc/w4vpcp

**Comment by NoobierNoob** [comment] 2020-12-17 19:04
Redownload it, it was fixed. You using an older version.

**Comment by berkay55** [comment] 2020-12-17 19:08
redownload but is not working
502 error persists bro

**Comment by NoNameoN-A** [comment] 2020-12-17 20:10
Ok the problem of the "issue" is fixed.
This is an else problem that can be solved with this [solution](https://github.com/NoNameoN-A/TikTok-Follow-Heart-Views-Bot/issues/11#issuecomment-740763849)

**Comment by berkay55** [comment] 2020-12-17 20:51
so how can i do
I did what you said, dns changed but the problem continues

**Comment by NoNameoN-A** [comment] 2020-12-18 07:21
Do You have a vpn opened?

**Comment by berkay55** [comment] 2020-12-18 14:54
no,
but i use VPN, not is working

**Comment by NoNameoN-A** [comment] 2020-12-18 14:56
so do you use a vpn?

**Comment by berkay55** [comment] 2020-12-18 15:15
no vpn

**Comment by NoNameoN-A** [comment] 2020-12-18 15:21
then i don't know how can i help you :-/ you have a problem with your connection

**Comment by berkay55** [comment] 2020-12-18 15:26
Should I use vpn?

**Comment by NoobierNoob** [comment] 2020-12-18 15:30
Hey @berkay55 , if you go to line 123 in the code and change the url to "https://ketuy.com/", see if that works. vipto.de just redirects to this site so maybe if you just connect to it directly.

**Comment by NoobierNoob** [comment] 2020-12-18 15:32
> Hey @berkay55 , if you go to line 123 in the code and change the url to "https://ketuy.com/", see if that works. vipto.de just redirects to this site so maybe if you just connect to it directly.

Also it does look like their view bot is marked as "soon will be update" so the bot will not work at the moment.

**Comment by berkay55** [comment] 2020-12-18 15:33
https://prnt.sc/w5hdqv
I'm input from turkey, so I wonder if the problem did

**Comment by NoobierNoob** [comment] 2020-12-18 15:36
> https://prnt.sc/w5hdqv
> I'm input from turkey, so I wonder if the problem did

Hmm.. I tried connecting using a Turkey VPN and it looks like I got an error 502. I have a version that uses proxies but it's extremely hit or miss with when it works or not since it uses a free proxy list. I can upload that version onto my page if you want so you can use that one.

**Comment by berkay55** [comment] 2020-12-18 15:37
yes i would love to
So I am waiting for news from you bro

**Comment by NoobierNoob** [comment] 2020-12-18 15:44
> yes i would love to
> So I am waiting for news from you bro

If you go onto my page, it should be labeled under "TikTok-Views-Follow-Heart-Proxy.py
Before running, 
1) run "pip install free-proxy" in command prompt 
2) change the file location link on the driver = webdriver on line 20 to where your .exe is
3) Change URL of TikTok video

**Comment by berkay55** [comment] 2020-12-18 15:51
https://prnt.sc/w5hrfb
thank you for the update
but the problem continues

I set up a free proxy first, then ran the bot, again it did not enter the site

**Comment by NoobierNoob** [comment] 2020-12-18 15:54
> https://prnt.sc/w5hrfb
> thank you for the update
> but the problem continues
> 
> I set up a free proxy first, then ran the bot, again it did not enter the site

Try running it again and again. Sometimes it will throw up errors and other times it will work. Like I said, it's extremely hit or miss.

**Comment by LIVEMTC** [comment] 2020-12-20 12:58
The site changed it so it won't allow pc user's to access it. I found a solution by just spoofing the browser into a mobile browser allowing you to never get to that 502 error road block.

**Comment by berkay55** [comment] 2020-12-20 15:45
is great bro
will you publish?

**Comment by NoNameoN-A** [comment] 2020-12-21 08:11
write a comment where you will explain your problem and your solution, I will publish a link on the primary page

**Comment by berkay55** [comment] 2020-12-21 13:58
i cant connect
502 error

**Comment by NoNameoN-A** [comment] 2020-12-21 14:59
if you are unable to access the site despite our support then you may have been banned.
The problem is with the site and not my repository, try to contact the owner via email -> sergey.plati@pm.me

**Closed by NoNameoN-A** 2020-12-21 14:59 UTC
