### ISSUE TITLE
[ERROR] Getting Default Adapter failed.

### ISSUE THREAD

**Issue by LeCupidity** [NoNameoN-A/TikTok-Follow-Heart-Views-Bot#27] opened 2021-01-12 20:29 UTC
![image](https://user-images.githubusercontent.com/77359869/104368954-b20f8300-5514-11eb-8e1e-8ff1a52ee025.png)
Getting error : 
[13764:9916:0112/202305.336:ERROR:device_event_log_impl.cc(211)] [20:23:05.336] Bluetooth: bluetooth_adapter_winrt.cc:1073 Getting Default Adapter failed.

**Comment by NoNameoN-A** [comment] 2021-01-13 07:34
I never seen this error... Bluetooth? I don't use Bluetooth in my code... try to turn off your Bluetooth i think that the problem isn't from my code

**Comment by LeCupidity** [comment] 2021-01-13 11:39
> I never seen this error... Bluetooth? I don't use Bluetooth in my code... try to turn off your Bluetooth i think that the problem isn't from my code

I don't have a Bluetooth & it's not a bug with your code, quite sure it's a problem with Selenium :/

**Comment by NoNameoN-A** [comment] 2021-01-13 13:01
ok however i don't close this issue :+1: good lucky 😁 :+1:

**Comment by NoNameoN-A** [comment] 2021-01-15 17:21
# VIDEO FOR BEGINNERS - Windows aviable
If you are a beginners release a star this repository, follow me and send me a screenshot on the email alessandrogreco@hacari.org, i will send you a video where i'll show you what you must to do for solve the errors and for make it work

[Email](mailto:alessandrogreco@hacari.org)
[Repository](https://github.com/NoNameoN-A/TikTok-Follow-Heart-Views-Bot#video-for-beginners---windows-aviable)

**Closed by NoNameoN-A** 2021-01-15 17:21 UTC
Labels: error
