### ISSUE TITLE
Kali Linux generic error

### ISSUE THREAD

**Issue by damramilor** [NoNameoN-A/TikTok-Follow-Heart-Views-Bot#38] opened 2021-01-28 17:07 UTC
![screenshot2](https://user-images.githubusercontent.com/72382383/106172698-2b110a80-61a4-11eb-9b3f-8136e4a54bf2.png)
I don't have the text I marked in the photo

and

![screenshot1](https://user-images.githubusercontent.com/72382383/106172761-3b28ea00-61a4-11eb-9e7d-a0ecb8a96284.JPG)
not opened

**Comment by NoNameoN-A** [comment] 2021-01-29 15:15
you must insert your link... what you see is a tiktok video from my account like this https://www.tiktok.com/@github_nonameon/video/6898692248968400130

**Comment by damramilor** [comment] 2021-01-29 16:41
![screen](https://user-images.githubusercontent.com/72382383/106302124-9bce2a80-6269-11eb-8546-781db9f4a334.JPG)
I wrote your TikTok video to try but it didn't work. Where am I making a mistake?



My Bot.py codes


from selenium import webdriver
from selenium.webdriver.support.ui import Select
import pyfiglet
from os import system
from time import sleep
import sys

def loop1():
    global i
    sleep(10)
    try:
        driver.find_element_by_xpath("/html/body/div[4]/div[1]/div[3]/div/div[4]/div/button").click()
    except:
        print("You didn't solve the captcha yet. Need to refresh to avoid endless loop.")
        driver.refresh()
        loop1()
    try:
        sleep(2)
        driver.find_element_by_xpath("//*[@id=\"sid4\"]/div/div/div/form/div/input").send_keys(vidUrl)
        sleep(1)
        driver.find_element_by_xpath("//*[@id=\"sid4\"]/div/div/div/form/div/div/button").click()
        sleep(2)
        driver.find_element_by_xpath("//*[@id=\"c2VuZC9mb2xsb3dlcnNfdGlrdG9V\"]/div[1]/div/form/button").click()
        sleep(10)
        driver.refresh()
        i += 1
        total = i * 500
        print("Views success delivered! Total", total,"views")
        sleep(80)
        loop1()
    except:
        print("An error occured. Now will retry again")
        driver.refresh()
        sleep(20)
        loop1()

def loop2():
    sleep(10)
    try:
        driver.find_element_by_xpath("/html/body/div[4]/div[1]/div[3]/div/div[2]/div/button").click()
    except:
        print("You didn't solve the captcha yet. Need to refresh to avoid endless loop.")
        driver.refresh()
        loop2()
    try:
        sleep(2)
        driver.find_element_by_xpath("/html/body/div[4]/div[3]/div/div/div/form/div/input").send_keys(vidUrl)
        sleep(1)
        driver.find_element_by_xpath("/html/body/div[4]/div[3]/div/div/div/form/div/div/button").click()
        sleep(10)
        driver.find_element_by_xpath("/html/body/div[4]/div[3]/div/div/div/div/div[1]/div/form/button").click()
        sleep(10)
        hearts = driver.find_element_by_xpath('//*[@id="c2VuZE9nb2xsb3dlcnNfdGlrdG9r"]/span').text
        sleep(55)
        print(hearts," Success delivered!")
        sleep(100)
        driver.refresh()
        sleep(200)
        loop2()
    except:
        print("An error occured. Now will retry again")
        driver.refresh()
        sleep(355)
        loop2()

def loop3():
    sleep(10)
    try:
        driver.find_element_by_xpath("/html/body/div[4]/div[1]/div[3]/div/div[3]/div/button").click()
    except:
        print("You didn't solve the captcha yet. Need to refresh to avoid endless loop.")
        driver.refresh()
        loop2()
    try:
        sleep(2)
        driver.find_element_by_xpath("/html/body/div[4]/div[4]/div/div/div/form/div/input").send_keys(vidUrl)
        sleep(1)
        driver.find_element_by_xpath("/html/body/div[4]/div[4]/div/div/div/form/div/div/button").click()
        sleep(5)
        driver.find_element_by_xpath("/html/body/div[4]/div[4]/div/div/div/div/div[1]/div/form/button").click()
        sleep(5)
        driver.find_element_by_xpath("/html/body/div[4]/div[4]/div/div/div/div/form/ul/li/div/button").click()
        sleep(47)
        driver.refresh()
        print("Liked :D")
        loop3()
    except:
        print("An error occured. Now will retry again")
        driver.refresh()
        sleep(50)
        loop3()

def loop4():
    sleep(20)
    wait_time = 660 #11 minutes
    try:
        driver.find_element_by_xpath("/html/body/div[4]/div[1]/div[3]/div/div[1]/div/button").click() #Followers
    except:
        print("You didn't solve the captcha yet. Need to refresh to avoid endless loop.")
        driver.refresh()
        loop4()
    try:
        sleep(20)
        driver.find_element_by_xpath("/html/body/div[4]/div[2]/div/div/div/form/div/input").send_keys(vidUrl) #Write
        sleep(2)
        driver.find_element_by_xpath("//*[@id=\"sid\"]/div/div/div/form/div/div/button").click() #Search
        sleep(20)
        driver.find_element_by_xpath("//*[@id=\"c2VuZF9mb2xsb3dlcnNfdGlrdG9r\"]/div[1]/div/form/button").click() #AddFollowers
        sleep(wait_time/3)
        print("Success delivered")
        sleep(wait_time/3)
        driver.refresh()
        sleep(wait_time/3)
        loop4()
    except:
        print("Oops!", sys.exc_info()[0], "occurred.")
        print("An error occurred. Now will retry again")
        driver.refresh()
        sleep(wait_time)
        loop4()
def loop5():
    sleep(1000)
    driver.refresh()
    print("Reload")
    loop5()

print("Author: https://github.com/NoNameoN-A")



vidUrl = "https://www.tiktok.com/@github_nonameon/video/6898692248968400130"

bot = input("What do you want to do?\n1 - Auto views(500)\n2 - Auto hearts\n3 - Auto (FIRST) comments heart\n4 - Auto followers\n5 - Simple reload\n")
i = 0

chrome_options = webdriver.ChromeOptions()
#chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')
driver = webdriver.Chrome('/root/Downloads/TikTok-Follow-Heart-Views-Bot-main/chromedriver',chrome_options=chrome_options) #Change it

driver.get("https://vipto.de/")

if bot == 1:
    loop1()
elif bot == 2:
    loop2()
elif bot == 3:
    loop3()
elif bot == 4:
    loop4()
else:
    loop5()

**Comment by NoNameoN-A** [comment] 2021-01-29 20:15
Edit this with your link ![This](https://i.ibb.co/ZGSk6BZ/asd.png)

**Comment by damramilor** [comment] 2021-01-29 21:34
![screen](https://user-images.githubusercontent.com/72382383/106329526-a355f980-6292-11eb-87f9-3c973aca5208.JPG)
I wrote my own TikTok link it didn't work again.

**Comment by NoNameoN-A** [comment] 2021-01-30 09:10
I never used Kali so i don't know if the problem is for the OS because i haven't problem on Ubuntu, Windows and MacOS... so i don't close the issue :+1:

**Comment by NoNameoN-A** [comment] 2021-02-13 19:42
Hi the problem can be for selenium, we have detected a bug... when we solve it i'll say you then we can try again. Thanks for the patience

**Comment by NoNameoN-A** [comment] 2021-03-07 08:24
Try with new file

**Closed by NoNameoN-A** 2021-03-07 08:24 UTC
Labels: error
